version: "3.9"

services:
  db:
    image: postgres:16
    container_name: auth-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: psql
      POSTGRES_DB: authdb
    ports:
      - "5432:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data

  auth-service:
    build: ./auth-service
    container_name: auth-service
    volumes:
      - ./auth-service:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - DATABASE_URL=postgres://postgres:psql@auth-db:5432/authdb
      - JWT_SECRET=4f77bcb6c75e30ccea23a19249d13b435dbc058d6c0fb2b47edd911f623b850cea4057b7b75e3ac033d355ce74e9a3e0ba10024177c85849212d4b8e450c3c65
    depends_on:
      - db
    ports:
      - "5001:5001"


  gateway-service:
    build: ./gateway-service
    container_name: gateway-service
    volumes:
      - ./gateway-service:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - AUTH_SERVICE_URL=http://auth-service:5001
    ports:
      - "5000:5000"

volumes:
  auth_db_data:
